[package]
name = "ic-lightclient-types"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.10"
serde = { version = "1.0.219", features = ["derive"] }
ic-lightclient-ethereum = { path = "../ethereum" }
ic-agent = "0.40.0"
alloy-primitives = { version = "1.0.0", features = ["serde"] }