[package]
name = "ic-lightclient-types"
version = "0.1.0"
edition = "2021"

[dependencies]
candid.workspace = true
serde.workspace = true
ic_principal.workspace = true
alloy-primitives.workspace = true
anyhow.workspace = true